version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # volumes:
    #  - .:/home/app/library
    #  - /home/app/library/node_modules